swagger: "2.0"
info:
  description: Hypothetical shopping backend. Try the demos included on this page!
  version: "0.1"
  title: Toothpaste API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /shop:
    get:
      operationId: shop.list_items
      tags:
        - Browsing
      summary: Get a list of all items
      description: >
        Get the list of all items in the shop, sorted by title. If `in_stock_only` is `True`,
        get only items that are in stock. If `False` or not passed, get everything.
      parameters:
        - name: in_stock_only
          description: Request only in-stock items if True.
          in: query
          type: boolean
          required: False
      responses:
        200:
          description: Successfully got the list of items.
          schema:
            type: array
            items:
              properties:
                title:
                  type: string
                price:
                  type: number
                inventory_count:
                  type: integer
  /product/{itemname}:
    get:
      operationId: shop.find_one_item
      tags:
        - Browsing
      summary: Get a single item by name
      description: >
        Get the details of one item, given a matching name. If the name doesn't appear
        among shop items, panic. Try passing in `Turtle dove` or `Chachalaca`, then try
        passing in `asdf`.
      parameters:
        - name: itemname
          description: Find an item in the shop with this name.
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully got details of one product.
          schema:
            properties:
              title:
                type: string
              price:
                type: number
              inventory_count:
                type: integer
        404:
          description: Lookup failed. The named product doesn't exist in the shop.
  /buy/{itemname}:
    put:
      operationId: shop.buy
      tags:
        - Purchasing
      summary: Buy the named item
      description: >
        Attempt to buy the item with the matching name, reducing its quantity by 1. Get a
        404 if there's no such item and a 406 if the item's quantity is insufficient. Try
        passing in `Turtle dove` or `Chachalaca`, then try passing in `asdf`. Try buying
        an item until it's out of stock.
      parameters:
        - name: itemname
          description: Find and buy the shop item with this name. Its stock goes down by 1.
          in: path
          type: string
          required: True
      responses:
        200:
          description: Successfully found and purchased the named product. Return its price.
          schema:
            properties:
              price:
                type: number
        404:
          description: Purchase failed. The named product doesn't exist in the shop.
        406:
          description: Purchase failed. The named product is out of stock.